add wave /resizer_tb/vectornum
add wave /resizer_tb/errors
add wave /resizer_tb/s_data_i_pp
add wave /resizer_tb/s_keep_i_pp
add wave /resizer_tb/s_last_i_pp
add wave /resizer_tb/buffer_pp
add wave /resizer_tb/buffer_pp_test
add wave /resizer_tb/last_idx_pp
add wave /resizer_tb/last_idx_pp_test
add wave /resizer_tb/keep_idx_pp
add wave /resizer_tb/keep_idx_pp_test
add wave /resizer_tb/s_parsed_data_i_fifo
add wave /resizer_tb/s_last_idx_i_fifo
add wave /resizer_tb/s_keep_idx_i_fifo
add wave /resizer_tb/clk_i_fifo
add wave /resizer_tb/rst_i_fifo
add wave /resizer_tb/m_ready_i_fifo
add wave /resizer_tb/s_we_i_fifo
add wave /resizer_tb/m_full_o_fifo
add wave /resizer_tb/m_full_o_fifo_test
add wave /resizer_tb/m_empty_o_fifo
add wave /resizer_tb/m_empty_o_fifo_test
add wave /resizer_tb/m_last_o_fifo
add wave /resizer_tb/m_last_o_fifo_test
add wave /resizer_tb/m_data_o_fifo
add wave /resizer_tb/m_data_o_fifo_test
add wave /resizer_tb/m_keep_o_fifo
add wave /resizer_tb/m_keep_o_fifo_test
add wave /resizer_tb/clk_rszr
add wave /resizer_tb/rst_n_rszr
add wave /resizer_tb/s_data_i_rszr
add wave /resizer_tb/s_keep_i_rszr
add wave /resizer_tb/s_last_i_rszr
add wave /resizer_tb/s_valid_i_rszr
add wave /resizer_tb/s_ready_o_rszr
add wave /resizer_tb/s_ready_o_rszr_test
add wave /resizer_tb/m_data_o_rszr
add wave /resizer_tb/m_data_o_rszr_test
add wave /resizer_tb/m_keep_o_rszr
add wave /resizer_tb/m_keep_o_rszr_test
add wave /resizer_tb/m_last_o_rszr
add wave /resizer_tb/m_last_o_rszr_test
add wave /resizer_tb/m_valid_o_rszr
add wave /resizer_tb/m_valid_o_rszr_test
add wave /resizer_tb/m_ready_i_rszr
add wave /resizer_tb/stream_rescale_dut/clk_40MHZ
view structure
view signals
run -all
wave zoom full